/**
 * Ticket System components definiton
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type StatusType = 'OK' | 'WARNING' | 'ERROR';

export const StatusType = {
    OK: 'OK' as StatusType,
    WARNING: 'WARNING' as StatusType,
    ERROR: 'ERROR' as StatusType
};