/**
 * Ticket System components definiton
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the event what customers could purchse NFT ticket for
 */
export interface EEvent { 
    /**
     * Identifier of the event
     */
    eventId: string;
    /**
     * Name of the event
     */
    eventName?: string;
    /**
     * Indicates percentages going to the creator of the NFTTickets of the event
     */
    sellerFeeToPublisher?: string;
    /**
     * The organiser of the event
     */
    publisherOfTicket?: string;
    /**
     * The ticket pool
     */
    maximumTicketSellable?: number;
    /**
     * The current price of the NFT ticket
     */
    currentPriceOfTicket?: string;
    /**
     * The publisher of the NFTTicket being the venue, who gets the seller fee
     */
    feeForNetworkMaintainer?: number;
    /**
     * Image of the event that would be on tickets
     */
    eventImage?: string;
    /**
     * The start date of the event
     */
    startDateOfEvent?: string;
    /**
     * The end date of the event
     */
    endDateOfEvent?: string;
    /**
     * The pyhsical location of the event
     */
    locationOfEvent?: string;
}