/**
 * Ticket System components definiton
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the mintable and tradeable NFT ticket
 */
export interface ENFTTicket { 
    /**
     * Hash of the NFT ticket
     */
    ticketHash: string;
    /**
     * The current owner of the NFT ticket
     */
    currentOwnerOfTicket?: string;
    /**
     * The current price of the NFT ticket
     */
    currentPriceOfTicket?: string;
    /**
     * The previous owner of the NFT ticket
     */
    previousOwnerOfTicket?: string;
    /**
     * The previous price of the NFT ticket
     */
    previousPriceOfTicket?: string;
    /**
     * Date of minting
     */
    mintedAt?: string;
    /**
     * Date of last modification on the NFT ticket's state
     */
    lastTradedAt?: string;
    /**
     * The number of the NFT ticket out of the total capacity existing
     */
    ticketNumber?: number;
    /**
     * The number of the NFT ticket out of the total capacity existing
     */
    ticketType?: string;
    /**
     * Identifier of the event
     */
    eventId?: string;
    /**
     * Name of the event
     */
    eventName?: string;
    /**
     * Indicates percentages going to the creator of the NFTTickets of the event
     */
    sellerFeeToPublisher?: string;
    /**
     * The organiser of the event
     */
    publisherOfTicket?: string;
    /**
     * The ticket pool
     */
    maximumTicketSellable?: number;
    /**
     * Fee for network network maintainer
     */
    feeForNetworkMaintainer?: number;
    /**
     * Image of the NFT ticket
     */
    ticketImage?: string;
    /**
     * Image of the event that would be on tickets
     */
    eventImage?: string;
    /**
     * The start date of the event
     */
    startDateOfEvent?: string;
    /**
     * The end date of the event
     */
    endDateOfEvent?: string;
    /**
     * The pyhsical location of the event
     */
    locationOfEvent?: string;
    /**
     * Shows whether has been listed on the secondary market or not
     */
    isOnSecondaryMarket?: boolean;
}