# Custom configuration for router
config:
  components_dir: ./
  # Configuration directory for express gateway. It MUST contain all the config files for express gateway
  # Leave it if you don't really need
  config_dir: "./gateway"
  # The storage of the wallets
  wallet_dir: "../../wallet"
  # components_dir: ""
  # Custom handlers
  module_dir: "../module"
  # Connection file for the HLF 
  connection_file: dist/config/connection-dev.yaml
  openapi_file: dist/config/openapi/openapi.yaml
  inventory_file: dist/config/chaincode.inventory.yaml
